# Think about the syntax

## TASK 1: take a list of numbers, and filter out all negative ones
This could be useful to filter out values that are not valid from a list of instrumental readings

In [1]:
original_list = [10, 72, -21, 9, 29,  21, -4, 92, 86, -20, 95, 26, -7, 4, -1, 4, 77, 91, 56, 53]
filtered_list = [] # create an empty list for filtered values
for number in original_list: # start a loop that covers the original list
    if number >= 0: # check if the considered value is non-negative
        filtered_list.append(number) # put the valid values in the filtered list
print(filtered_list) # print the filtered list

## BONUS: create the new list and put data inside in a single row of code
filtered_list_bonus = [number for number in original_list if number >= 0] # it's a list comprehension!
print(filtered_list_bonus)

[10, 72, 9, 29, 21, 92, 86, 95, 26, 4, 4, 77, 91, 56, 53]
[10, 72, 9, 29, 21, 92, 86, 95, 26, 4, 4, 77, 91, 56, 53]


## TASK 2: what's the difference between numpy arrays and lists?
Create a list and a numpy array with the same data, then try some easy operations on them to see the different results

In [3]:
import numpy as np # import the necessary library
my_list = [0, 1, 2, 3, 4, 5] # create a list with numbers from 0 to 5 
my_array = np.array(my_list) # create a numpy array with the same values

# multiply list and array for a scalar (a single number)
print('Multiplication by a scalar (3)')
print(my_list * 3)
print(my_array * 3)

# sum list and array to a scalar (a single number)
print('Summing a number (28.7)')
#print(my_list + 28.7) # THIS GIVES AN ERROR, I'VE COMMENTED IT. You can't sum lists and numbers 
print(my_array + 28.7)

# sum list and array with themselves
print('Sum with oneself')
print(my_list + my_list)
print(my_array + my_array)

Multiplication by a scalar (3)
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
[ 0  3  6  9 12 15]
Summing a number (28.7)
[28.7 29.7 30.7 31.7 32.7 33.7]
Sum with oneself
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
[ 0  2  4  6  8 10]


## TASK 3: take a list of names and a list of phone numbers, and create a dictionary with entries name:phone number
This is because we never did exercises with dictionaries

In [4]:
names = ['Doctor', 'Rose', 'K9', 'Captain Jack']
phone_numbers = [555666, 555123, 555555, 555999]
phone_book = {} # create an empty dictionary where we'll store the numbers
for i in range(len(names)): # start a loop that can be used to go over both names and phone numbers
    phone_book[names[i]] = phone_numbers[i] # add entries to the dictionary
print(phone_book) # print the dictionary

{'Doctor': 555666, 'Rose': 555123, 'K9': 555555, 'Captain Jack': 555999}
